### ISSUE TITLE
Does not find Functor Composition Law

### ISSUE THREAD

**Issue by Fresheyeball** [rudymatela/speculate#4]
Providing `fmap`, `id`, and `.` to Speculate results in

```
_ :: Int  (holes: Int)
_ :: [Int]  (holes: [Int])
fmap :: (Int -> Int) -> [Int] -> [Int]
id :: Int -> Int
(.) :: (Int -> Int) -> (Int -> Int) -> Int -> Int

             id x == x
      (id . id) x == x
       fmap id xs == xs
fmap (id . id) xs == xs
```

which misses

`fmap f . fmap g == fmap (f . g)`

**Comment by rudymatela** [comment]
By default, Speculate does not treat functions as test values neither does it considers functions as `Eq` instances when building equations (`==`).  That is confirmed by the absence of the following line in the output heading:

     _ :: Int -> Int (holes: Int -> Int)

You can manually do this by declaring and providing `Listable`, `Eq` and `Ord` instances to Speculate.  I have [just added](https://github.com/rudymatela/speculate/commit/731f0b5cef717f112207a6ec45b2b1d712343a44) an [example showing how to treat functions as test values on Speculate](https://github.com/rudymatela/speculate/blob/master/eg/fun.hs) to the [eg folder](https://github.com/rudymatela/speculate/tree/master/eg).  It has `id`, `map` and `.` in the background and produces the following output:

    _ :: Int  (holes: Int)
    _ :: [Int]  (holes: [Int])
    _ :: Int -> Int  (holes: Int -> Int)
    map :: (Int -> Int) -> [Int] -> [Int]
    id :: Int -> Int
    (.) :: (Int -> Int) -> (Int -> Int) -> Int -> Int

              id x == x
           f (g x) == (f . g) x
         map id xs == xs
    map (f . g) xs == map f (map g xs)
            f . id == f
            id . f == f
       (f . g) . h == f . (g . h)

You can see that not only it prints the functor composition law, but it also prints associativity of function composition and identity of functions.


## Step by step process to configure functions as test values

1. Import LeanCheck's `Listable (a -> b)` instance:

        import Test.LeanCheck.Function

2. Declare two toy `Eq` and `Ord` instances for functions:

        import Test.LeanCheck.Error (errorToNothing)
        import Data.Function (on)

        funToList :: Listable a => (a -> b) -> [Maybe b]
        funToList f = map (errorToNothing . f) list

        instance (Listable a, Eq b) => Eq (a -> b) where
          (==) = (==) `on` (take 100 . funToList)

        instance (Listable a, Ord b) => Ord (a -> b) where
          compare = compare `on` (take 100 . funToList)

3. Manually provide those instances to Speculate using the `Args.instances` list:

        speculate args
          { instances = [ins "f" (undefined :: Int -> Int)]
          , ...
          }

4. Tell Speculate to generate variables ("holes") of `Int -> Int` type:

        speculate args
          { ...
          , constants = [ hole (undefined :: Int -> Int)
                        , ... ]
          }

5. run to get the following output:

        _ :: Int  (holes: Int)
        _ :: [Int]  (holes: [Int])
        _ :: Int -> Int  (holes: Int -> Int)
        map :: (Int -> Int) -> [Int] -> [Int]
        id :: Int -> Int
        (.) :: (Int -> Int) -> (Int -> Int) -> Int -> Int

                  id x == x
               f (g x) == (f . g) x
             map id xs == xs
        map (f . g) xs == map f (map g xs)
                f . id == f
                id . f == f
           (f . g) . h == f . (g . h)

## Further info

In a future version of Speculate, I will try to simplify steps 1 and 2 (by providing a single module with already made `Listable`, `Eq` and `Ord` instances for functions).

See also: [Speculate's "monad" example](https://github.com/rudymatela/speculate/blob/master/eg/monad.hs).

@Fresheyeball, let me know if you have any questions.  :-)

**Comment by rudymatela** [comment]
I have added three modules to Speculate providing the functionality I mentioned earlier:

* [Test.Speculate.Function](https://github.com/rudymatela/speculate/blob/master/src/Test/Speculate/Function.hs);
* [Test.Speculate.Function.A100](https://github.com/rudymatela/speculate/blob/master/src/Test/Speculate/Function/A100.hs);
* [Test.Speculate.Function.A1000](https://github.com/rudymatela/speculate/blob/master/src/Test/Speculate/Function/A1000.hs);

I hope they'll make it easier to bootstrap functions as test data for Speculate.

As you can see in [the eg/fun example](https://github.com/rudymatela/speculate/blob/master/eg/fun.hs), all you need now is 3 extra lines of code:

1. to `import Test.Speculate.Function.A100`;

2. to provide `instances = [ins "f" (undefined :: Int -> Int)]`;

3. to provide `hole (undefined :: Int -> Int)` in the `constants` list.

For an example, see [eg/fun](https://github.com/rudymatela/speculate/blob/master/eg/fun.hs).
