### ISSUE TITLE
Grading functions

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [rudymatela/speculate#6]
Would this be helpful in finding an optimized function for a or giving insight to nonlinear grading function?

**Comment by rudymatela** [comment]
@BebeSparkelSparkel I'm not sure I understand the question.  Could you elaborate a bit more?  Perhaps an example could help.

**Comment by rudymatela** [comment]
I'm provisionally closing this issue until further info is provided.  Just let me know and I'll reopen it.
