### ISSUE TITLE
document what instances must be given

### ISSUE THREAD

**Issue by jwaldmann** [rudymatela/speculate#8]
It is not clear what reified instances have to be added. The examples show that `Int` and `Bool` are built in, but some other types are not. Which, exactly? 

I  was assuming that it works for all instances that are known to leancheck, including `Test.LeanCheck.Util.Types.Nat`, but it does not.

I now assume that it works for all types that have instances of `Name`.
https://hackage.haskell.org/package/speculate-0.4.2/docs/Test-Speculate.html#t:Name

**Comment by rudymatela** [comment]
Thanks for the suggestion @jwaldmann.

The documentation and [README](https://github.com/rudymatela/speculate#readme) was surely lacking an explanation on this.

I have added a section now clearly detailing [how to deal with custom types and use the `reifyInstances` family of functions](https://github.com/rudymatela/speculate#supported-types).  I even explain how to deal with `Name` there and why is it needed.

@RSWilli may be interested in this, as it related to his issue #7.
