### ISSUE TITLE
TypeApplications for shorter/nicer code

### ISSUE THREAD

**Issue by jwaldmann** [rudymatela/speculate#9]
1. (no code change, but update example) The example has
```
 , constant "+"   ((+)  :: Int -> Int -> Int)
```
I think this looks much nicer
```
{-# language TypeApplications #-}
...
 , constant "+"   ((+)  @Int)
```
2. (code change) currently, we need a proxy argument
```
  , instances = [ reifyListable (0::N), ...
```
the "proxy" role could be made more clear by writing `undefined::N`, or by `Proxy :: Proxy N`, but I think this would be best:
```
  , instances = [ reifyListable @N, ...
```
This might require `AllowAmbiguousTypes`.

**Comment by rudymatela** [comment]
> I think this looks much nicer
> 
>     {-# language TypeApplications #-}
>     ...
>      , constant "+"   ((+)  @Int)

That's a good suggestion.  I have added a note on the [README](https://github.com/rudymatela/speculate#readme) mentioning this.

In favour of backwards compatibility, I usually try to stay away from language extensions where possible when writing libraries.  Speculate does work on GHCs down to version 7.8 and I suspect it could be backported further to 7.6 and 7.4 with minor changes.  (cf. [TypeApplications started exiting in GHC 7.8](https://gitlab.haskell.org/ghc/ghc/-/wikis/language-pragma-history#changes-in-ghc-80))

> the "proxy" role could be made more clear by writing `undefined::N`, or by `Proxy :: Proxy N`, but I think this would be best:

The first option, `undefined :: N` is the one I use most frequently in the [examples folder](https://github.com/rudymatela/speculate/tree/master/eg).  I'm aware of `Proxy` but ended up deciding to go for a more "old-school" solution.

Incidentally: I'm from the time before [TypeApplications](https://gitlab.haskell.org/ghc/ghc/-/wikis/language-pragma-history#changes-in-ghc-80), I even created a [LeanCheck module with a "DSL of sorts" for type binding](https://hackage.haskell.org/package/leancheck-0.9.3/docs/Test-LeanCheck-Utils-TypeBinding.html).   The original example would become:

    , constant "+" ((+) -:> int)

But of course, in today's times, it is better to use the more widely known TypeApplications pragma.  This is more of a curiosity now.
